# Generated by Django 3.0.7 on 2020-07-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='Em validação', max_length=12),
        ),
    ]
