# Generated by Django 3.0.7 on 2020-07-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200702_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='code',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
